# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# bundle exec jekyll serve --livereload --drafts --profile

# bundle exec jekyll serve --livereload

# Site settings
title:       'Get Info'
extitle:     '⌘I  Get Info'
email:       ''
description: 'Blog of independent video game developer and digital media artist Matt Sephton. Featuring vintage Macintosh, game development, digital artwork, Japanese esoterica, video game reviews, hacks and tips, and much more.'
author:      'Matt Sephton'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://blog.gingerbeardman.com' # The base hostname & protocol for your site
homepage:    'https://www.gingerbeardman.com' # other link
cdn:         'https://cdn.gingerbeardman.com' # cdn link
github:      ''
instagram:   ''
facebook:    ''

google_analytics: 'G-JVMQWHYEWV'

twitter:
  username: gingerbeardman
  card: summary

donate:
  kofi: https://ko-fi.com/gingerbeardman
  patreon: https://www.patreon.com/gingerbeardman
  paypalme: https://paypal.me/mattsephton
  stripe: https://donate.stripe.com/cN24hg7yTbqF6Aw288

social:
  name: Matt Sephton
  links:
    - https://twitter.com/gingerbeardman

# Jekyll specific

markdown:  kramdown
permalink: pretty

sass:
  style: compressed

plugins:
  - jekyll-regex-replace
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-loading-lazy
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages
  - search.json

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Paginate
paginate:  10
paginate_path: "/page/:num/"

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Defaults

defaults:
  -
    scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext
  -
    scope:
      path: "files/**"
    values:
      sitemap: false
